global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: check-this-out
    static_configs:
      - targets: ['checkthisout:80']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']